#!/bin/bash
set -e

echo "----------------------------------------------------------------"
echo "STARTING MERGED TEST RUNNER"
echo "----------------------------------------------------------------"

# --- PHASE 1: UNIT TESTS ---
echo ""
echo ">> [1/2] Calculating UNIT TEST Filter..."
UNIT_FILTER=$(python3 .github/scripts/manage_test_state.py get_args --state-file .state/test-status.json --suite unit)
echo ">> Unit Filter: $UNIT_FILTER"

if [ "$UNIT_FILTER" == "NONE" ]; then
  echo ">> ✅ All Unit Tests previously passed. Skipping."
elif [ "$UNIT_FILTER" == "RUN_ALL" ]; then
  echo ">> 🔄 Running ALL Unit Tests..."
  ./gradlew testDebugUnitTest --build-cache --configuration-cache
else
  echo ">> ⚠️ Rerunning FAILED Unit Tests..."
  # $UNIT_FILTER contains the --tests flags generated by python
  ./gradlew testDebugUnitTest $UNIT_FILTER --build-cache --configuration-cache
fi

# Update State for Unit Tests immediately
python3 .github/scripts/manage_test_state.py update_state \
  --state-file .state/test-status.json \
  --xml-dir app/build/test-results/testDebugUnitTest \
  --suite unit

# --- PHASE 2: ANDROID TESTS ---
echo ""
echo ">> [2/2] Calculating ANDROID Filter..."
ANDROID_FILTER=$(python3 .github/scripts/manage_test_state.py get_args --state-file .state/test-status.json --suite android)
echo ">> Android Filter: $ANDROID_FILTER"

if [ "$ANDROID_FILTER" == "NONE" ]; then
  echo ">> ✅ All Android Tests previously passed. Skipping."
elif [ "$ANDROID_FILTER" == "RUN_ALL" ]; then
  echo ">> 🔄 Running ALL Android Tests..."
  ./gradlew connectedCheck --parallel --build-cache --configuration-cache
else
  echo ">> ⚠️ Rerunning FAILED Android Tests..."
  ./gradlew connectedCheck -Pandroid.testInstrumentationRunnerArguments.class=$ANDROID_FILTER --parallel --build-cache --configuration-cache
fi

# Update State for Android Tests
python3 .github/scripts/manage_test_state.py update_state \
  --state-file .state/test-status.json \
  --xml-dir app/build/outputs/androidTest-results/connected \
  --suite android

echo "----------------------------------------------------------------"
echo "TEST RUNNER COMPLETE"
echo "----------------------------------------------------------------"